//! Turns `config.toml` into the constants `src/config.rs` exposes, and into the
//! onboarding artifacts under `commissioning/`.
//!
//! Build-time rather than runtime for two reasons: the device has no filesystem to
//! read a config from at boot, and several of the values land in `const` contexts
//! that a runtime value could not satisfy (`ThermostatHooks::ABS_MIN_HEAT_SETPOINT`,
//! `ElecPwrMeasHooks::ACCURACY`).
//!
//! `config.local.toml`, if it exists, is merged over `config.toml` key by key so that
//! a differently-rated unit builds from a clean tree. The merged table is then
//! deserialised into a `deny_unknown_fields` struct, which is what makes a typo in
//! *either* file a build error with a line and column rather than a silently ignored
//! key.
//!
//! The onboarding artifacts are the same QR payload and manual pairing code the
//! firmware prints at boot, written out where a workstation can print them - see
//! [`emit_onboarding`]. They are generated by `rs-matter` itself rather than by a
//! second implementation of the Core spec's bit packing, which is why this script
//! depends on that crate.
//!
//! This is a host build script, so `std` is available and none of the crate's
//! `no_std` rules apply here.

use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs};

use rs_matter::dm::devices::test::TEST_DEV_DET;
use rs_matter::pairing::qr::{
    no_optional_data, CommFlowType, NoOptionalData, Qr, QrPayload, QrTextType,
};
use rs_matter::pairing::DiscoveryCapabilities;
use rs_matter::sc::pase::{Spake2pVerifierPassword, Spake2pVerifierPasswordRef};
use rs_matter::BasicCommData;
use serde::Deserialize;
use toml::{Table, Value};

/// The committed defaults, documenting every key.
const CONFIG: &str = "config.toml";

/// Optional, gitignored, partial: overrides [`CONFIG`] key by key.
const LOCAL_CONFIG: &str = "config.local.toml";

/// Where the onboarding artifacts land, relative to the crate root. Gitignored:
/// these are generated, and on a tree with a `config.local.toml` they are also the
/// codes of one particular board.
const ONBOARDING_DIR: &str = "commissioning";

/// The QR code's quiet zone, in modules. Four is the minimum the standard allows,
/// and what the firmware prints.
const QR_BORDER: u8 = 4;

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Config {
    heater: Heater,
    device: Device,
    commissioning: Commissioning,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Heater {
    element_watts: u32,
    min_setpoint_celsius: i32,
    max_setpoint_celsius: i32,
    default_setpoint_celsius: i32,
    metering_accuracy_percent: f64,
    circuit_max_watts: u32,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Device {
    vendor_name: String,
    product_name: String,
    product_label: String,
    part_number: String,
    hardware_version: u16,
    hardware_version_string: String,
    software_version: u32,
    software_version_string: String,
    manufacturing_date: String,
    device_name: String,
    serial_number: String,
    unique_id_prefix: String,
}

#[derive(Deserialize)]
#[serde(deny_unknown_fields)]
struct Commissioning {
    passcode: u32,
    discriminator: u16,
}

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed={CONFIG}");
    // Fires when the file appears, too - a `rerun-if-changed` on a path that does not
    // exist yet is honoured rather than ignored.
    println!("cargo::rerun-if-changed={LOCAL_CONFIG}");

    let config = match load() {
        Ok(config) => config,
        Err(err) => fail(&err),
    };

    if let Err(err) = validate(&config) {
        fail(&err);
    }

    let out = Path::new(&env::var_os("OUT_DIR").expect("cargo sets OUT_DIR")).join("config.rs");

    if let Err(err) = fs::write(&out, emit(&config)) {
        fail(&format!("could not write {}: {err}", out.display()));
    }

    if let Err(err) = emit_onboarding(&config) {
        fail(&err);
    }
}

/// Report a configuration problem and stop the build.
///
/// `cargo::error` puts it in the same place a compile error goes; the panic is what
/// actually fails the build, and its message is suppressed so the diagnostic is not
/// printed twice.
fn fail(message: &str) -> ! {
    for line in message.lines() {
        println!("cargo::error={line}");
    }

    std::process::exit(1);
}

/// Parse [`CONFIG`], merge [`LOCAL_CONFIG`] over it, and deserialise the result.
fn load() -> Result<Config, String> {
    let mut merged = read_table(CONFIG)?.ok_or_else(|| {
        format!("{CONFIG} is missing - it carries the defaults and has to be present")
    })?;

    if let Some(local) = read_table(LOCAL_CONFIG)? {
        merge(&mut merged, local);
    }

    // Deserialising the *merged* table rather than each file separately is what lets
    // `config.local.toml` be partial while still catching unknown keys in it.
    Config::deserialize(Value::Table(merged))
        .map_err(|err| format!("{CONFIG} (or {LOCAL_CONFIG}) is not valid configuration: {err}"))
}

fn read_table(path: &str) -> Result<Option<Table>, String> {
    let text = match fs::read_to_string(path) {
        Ok(text) => text,
        Err(err) if err.kind() == std::io::ErrorKind::NotFound => return Ok(None),
        Err(err) => return Err(format!("could not read {path}: {err}")),
    };

    text.parse::<Table>()
        .map(Some)
        .map_err(|err| format!("{path} is not valid TOML: {err}"))
}

/// Overlay `over` onto `base`, recursing into tables so a partial `[heater]` section
/// replaces only the keys it names.
fn merge(base: &mut Table, over: Table) {
    for (key, value) in over {
        match (base.get_mut(&key), value) {
            (Some(Value::Table(base)), Value::Table(over)) => merge(base, over),
            (_, value) => {
                base.insert(key, value);
            }
        }
    }
}

fn validate(config: &Config) -> Result<(), String> {
    let Config {
        heater,
        device,
        commissioning,
    } = config;

    // Basic Information's string maxima, from the doc comments on `BasicInfoConfig`
    // in `../rs-matter/rs-matter/src/dm/clusters/basic_info.rs`. A longer value would
    // be truncated or rejected by a controller rather than caught here.
    for (key, value, max) in [
        ("device.vendor_name", &device.vendor_name, 32),
        ("device.product_name", &device.product_name, 32),
        ("device.product_label", &device.product_label, 64),
        ("device.part_number", &device.part_number, 32),
        (
            "device.hardware_version_string",
            &device.hardware_version_string,
            64,
        ),
        (
            "device.software_version_string",
            &device.software_version_string,
            64,
        ),
        ("device.manufacturing_date", &device.manufacturing_date, 16),
        ("device.serial_number", &device.serial_number, 32),
    ] {
        let len = value.chars().count();

        if len > max {
            return Err(format!(
                "{key} is {len} characters; the Basic Information cluster allows at most {max}"
            ));
        }
    }

    if device.vendor_name.is_empty() || device.product_name.is_empty() {
        return Err("device.vendor_name and device.product_name may not be empty".into());
    }

    if device.device_name.is_empty() {
        return Err(
            "device.device_name may not be empty - it is what a commissioner shows in its \
             \"device found\" prompt"
                .into(),
        );
    }

    // The generated UniqueID is the prefix followed by twelve hex digits of the
    // factory MAC, and the attribute allows 64 characters.
    let unique_id_len = device.unique_id_prefix.chars().count() + 12;

    if unique_id_len > 64 {
        return Err(format!(
            "device.unique_id_prefix is too long: with the twelve hex digits of the factory MAC \
             it would make a {unique_id_len}-character UniqueID, and the attribute allows 64"
        ));
    }

    validate_date(&device.manufacturing_date)?;

    if heater.element_watts == 0 {
        return Err("heater.element_watts must be greater than zero".into());
    }

    if heater.element_watts > heater.circuit_max_watts {
        return Err(format!(
            "heater.element_watts ({}) exceeds heater.circuit_max_watts ({}), so the element \
             would draw more than the range the meter advertises",
            heater.element_watts, heater.circuit_max_watts
        ));
    }

    // Both wattages are emitted as `u16`, because the element's rating is a runtime
    // value the Mode Select cluster can change and the circuit maximum is the ceiling
    // every such change is checked against. A `u16` is 65 kW of headroom over a
    // 16 A circuit; the bound exists so the cast cannot silently wrap, not because
    // anybody will approach it.
    if heater.circuit_max_watts > u32::from(u16::MAX) {
        return Err(format!(
            "heater.circuit_max_watts ({}) is above {}, which is as much as the \
             runtime element rating can carry",
            heater.circuit_max_watts,
            u16::MAX
        ));
    }

    if heater.min_setpoint_celsius >= heater.max_setpoint_celsius {
        return Err(format!(
            "heater.min_setpoint_celsius ({}) must be below heater.max_setpoint_celsius ({})",
            heater.min_setpoint_celsius, heater.max_setpoint_celsius
        ));
    }

    if !(heater.min_setpoint_celsius..=heater.max_setpoint_celsius)
        .contains(&heater.default_setpoint_celsius)
    {
        return Err(format!(
            "heater.default_setpoint_celsius ({}) is outside the configured range {}..={}",
            heater.default_setpoint_celsius,
            heater.min_setpoint_celsius,
            heater.max_setpoint_celsius
        ));
    }

    // The three setpoints are served as hundredths of a degree in an `i16`.
    for (key, celsius) in [
        ("heater.min_setpoint_celsius", heater.min_setpoint_celsius),
        ("heater.max_setpoint_celsius", heater.max_setpoint_celsius),
        (
            "heater.default_setpoint_celsius",
            heater.default_setpoint_celsius,
        ),
    ] {
        if centidegrees(celsius).is_none() {
            return Err(format!(
                "{key} ({celsius} C) does not fit the cluster's hundredths-of-a-degree i16, \
                 whose range is {}..={} C",
                i16::MIN / 100,
                i16::MAX / 100
            ));
        }
    }

    accuracy_hundredths(heater.metering_accuracy_percent)?;

    // 12-bit, per the Core spec.
    if commissioning.discriminator > 0xfff {
        return Err(format!(
            "commissioning.discriminator ({}) does not fit 12 bits; the maximum is 4095",
            commissioning.discriminator
        ));
    }

    validate_passcode(commissioning.passcode)?;

    Ok(())
}

/// `YYYYMMDD`, and a date that exists.
fn validate_date(date: &str) -> Result<(), String> {
    let complain =
        || format!("device.manufacturing_date ({date:?}) must be a real calendar date as YYYYMMDD");

    if date.len() != 8 || !date.bytes().all(|b| b.is_ascii_digit()) {
        return Err(complain());
    }

    let (year, month, day) = (
        date[..4].parse::<u32>().map_err(|_| complain())?,
        date[4..6].parse::<u32>().map_err(|_| complain())?,
        date[6..].parse::<u32>().map_err(|_| complain())?,
    );

    let leap = year % 4 == 0 && (year % 100 != 0 || year % 400 == 0);

    let days = match month {
        1 | 3 | 5 | 7 | 8 | 10 | 12 => 31,
        4 | 6 | 9 | 11 => 30,
        2 if leap => 29,
        2 => 28,
        _ => return Err(complain()),
    };

    if day == 0 || day > days {
        return Err(complain());
    }

    Ok(())
}

/// The passcode constraints from Core spec 5.1.7.1: a 27-bit value, not zero, and not
/// one of the twelve the spec calls out as too easily guessed.
fn validate_passcode(passcode: u32) -> Result<(), String> {
    /// Section 5.1.7.1's list of invalid passcodes.
    const FORBIDDEN: [u32; 12] = [
        0, 11111111, 22222222, 33333333, 44444444, 55555555, 66666666, 77777777, 88888888,
        99999999, 12345678, 87654321,
    ];

    /// The largest passcode that encodes in the manual pairing code's 27 bits.
    const MAX: u32 = 0x5f5e0fe;

    if passcode > MAX {
        return Err(format!(
            "commissioning.passcode ({passcode}) is above the maximum {MAX} (0x5F5E0FE)"
        ));
    }

    if FORBIDDEN.contains(&passcode) {
        return Err(format!(
            "commissioning.passcode ({passcode:08}) is one of the twelve values Core spec 5.1.7.1 \
             forbids as too easily guessed"
        ));
    }

    Ok(())
}

/// Whole degrees Celsius to the hundredths the Thermostat cluster serves.
fn centidegrees(celsius: i32) -> Option<i16> {
    celsius.checked_mul(100).and_then(|c| i16::try_from(c).ok())
}

/// Percent to the hundredths of a percent `MeasurementAccuracyRange` wants.
fn accuracy_hundredths(percent: f64) -> Result<u16, String> {
    if !(0.0..=100.0).contains(&percent) {
        return Err(format!(
            "heater.metering_accuracy_percent ({percent}) must be between 0 and 100"
        ));
    }

    let hundredths = percent * 100.0;

    // The attribute is in hundredths of a percent, so anything finer is a value the
    // device cannot actually express - better to say so than to round it silently.
    if (hundredths - hundredths.round()).abs() > 1e-6 {
        return Err(format!(
            "heater.metering_accuracy_percent ({percent}) is finer than the hundredth of a \
             percent the cluster can express"
        ));
    }

    Ok(hundredths.round() as u16)
}

/// The generated module body.
fn emit(config: &Config) -> String {
    let Config {
        heater,
        device,
        commissioning,
    } = config;

    // Every one of these was checked in `validate`.
    let min_setpoint = centidegrees(heater.min_setpoint_celsius).unwrap();
    let max_setpoint = centidegrees(heater.max_setpoint_celsius).unwrap();
    let default_setpoint = centidegrees(heater.default_setpoint_celsius).unwrap();
    let accuracy = accuracy_hundredths(heater.metering_accuracy_percent).unwrap();

    // Empty means "the crate version", which is the useful default for a firmware
    // whose SoftwareVersionString nobody wants to keep in step by hand.
    let sw_ver_str = if device.software_version_string.is_empty() {
        env::var("CARGO_PKG_VERSION").expect("cargo sets CARGO_PKG_VERSION")
    } else {
        device.software_version_string.clone()
    };

    // Empty means "derive it from the factory MAC" - see the key's comment in
    // `config.toml` for why that is the right default.
    let serial_no = if device.serial_number.is_empty() {
        "None".to_string()
    } else {
        format!("Some({:?})", device.serial_number)
    };

    let element_watts = heater.element_watts;
    let circuit_max_watts = heater.circuit_max_watts;
    let circuit_max_power_mw = i64::from(heater.circuit_max_watts) * 1000;

    let vendor_name = &device.vendor_name;
    let product_name = &device.product_name;
    let product_label = &device.product_label;
    let part_number = &device.part_number;
    let hardware_version = device.hardware_version;
    let hardware_version_string = &device.hardware_version_string;
    let software_version = device.software_version;
    let manufacturing_date = &device.manufacturing_date;
    let device_name = &device.device_name;
    let unique_id_prefix = &device.unique_id_prefix;
    let passcode = commissioning.passcode;
    let discriminator = commissioning.discriminator;

    let mut out = String::new();

    let _ = write!(
        out,
        r#"// @generated by build.rs from config.toml - do not edit.
//
// Edit `config.toml` (or `config.local.toml`) and rebuild instead.

/// The heating element's rated power in watts, as the device comes up with nothing
/// stored.
///
/// Gated on the Mill's on/off bit, this is every power and energy reading the device
/// serves; there is no metering hardware to check it against. Only the *default*,
/// though: the Mode Select cluster on endpoint 2 can pick another rating, and what
/// it picks is persisted and wins from then on.
pub const DEFAULT_ELEMENT_WATTS: u16 = {element_watts};

/// The most the element may be told it is rated at, in watts.
///
/// The ceiling on every runtime change of the rating, because the accuracy range
/// `ElectricalPowerMeasurement` advertises is built from it: an element claiming
/// more than this would report an `ActivePower` above its own `MaxMeasuredValue`.
pub const CIRCUIT_MAX_WATTS: u16 = {circuit_max_watts};

/// The top of the reported power range, in milliwatts.
pub const CIRCUIT_MAX_POWER_MW: i64 = {circuit_max_power_mw};

/// The claimed accuracy of every reading, in hundredths of a percent.
pub const METER_ACCURACY: u16 = {accuracy};

/// `AbsMinHeatSetpointLimit`, in hundredths of a degree Celsius.
pub const ABS_MIN_HEAT_SETPOINT: i16 = {min_setpoint};

/// `AbsMaxHeatSetpointLimit`, in hundredths of a degree Celsius.
pub const ABS_MAX_HEAT_SETPOINT: i16 = {max_setpoint};

/// The setpoint a device with nothing to restore comes up with, in hundredths of a
/// degree Celsius.
pub const DEFAULT_HEATING_SETPOINT: i16 = {default_setpoint};

/// Basic Information's `VendorName`.
pub const VENDOR_NAME: &str = {vendor_name:?};

/// Basic Information's `ProductName`.
pub const PRODUCT_NAME: &str = {product_name:?};

/// Basic Information's `ProductLabel`.
pub const PRODUCT_LABEL: &str = {product_label:?};

/// Basic Information's `PartNumber`.
pub const PART_NUMBER: &str = {part_number:?};

/// Basic Information's `HardwareVersion`.
pub const HW_VER: u16 = {hardware_version};

/// Basic Information's `HardwareVersionString`.
pub const HW_VER_STR: &str = {hardware_version_string:?};

/// Basic Information's `SoftwareVersion`.
pub const SW_VER: u32 = {software_version};

/// Basic Information's `SoftwareVersionString`.
pub const SW_VER_STR: &str = {sw_ver_str:?};

/// Basic Information's `ManufacturingDate`, as `YYYYMMDD`.
pub const MANUFACTURING_DATE: &str = {manufacturing_date:?};

/// The name carried in the mDNS commissioning advertisement.
pub const DEVICE_NAME: &str = {device_name:?};

/// Basic Information's `SerialNumber`, or `None` to derive it from the factory MAC.
pub const SERIAL_NUMBER: Option<&str> = {serial_no};

/// Prefixed to the MAC-derived `UniqueID`.
pub const UNIQUE_ID_PREFIX: &str = {unique_id_prefix:?};

/// The commissioning passcode behind the printed pairing codes.
pub const PASSCODE: u32 = {passcode};

/// The 12-bit commissioning discriminator.
pub const DISCRIMINATOR: u16 = {discriminator};
"#
    );

    out
}

/// Write the onboarding artifacts into [`ONBOARDING_DIR`].
///
/// A board sealed inside a heater never shows its console, so the codes it would
/// print at boot have to exist somewhere a printer can reach. Nothing in them is
/// discovered at runtime - they are the `[commissioning]` passcode and discriminator,
/// the fixed test VID/PID, the standard commissioning flow and BLE as the only
/// discovery capability - so the build can produce them exactly.
///
/// "Exactly" up to one field. `rs-matter` folds `BasicInformation`'s `SerialNumber`
/// into the payload as optional TLV data when it is set, and ours is derived from the
/// chip's factory MAC, which this script cannot know. The generated payload therefore
/// omits it. That is the difference between the two `MT:` strings and the whole of it:
/// the serial is optional data a commissioner does not need, and both codes carry the
/// same discriminator and passcode, so both pair.
///
/// The artifacts are regenerated whenever the configuration changes. Deleting one
/// also brings them back, which is what the `rerun-if-changed` on the directory is
/// for - without it the build script would not run again until `config.toml` did.
/// That watch is why [`write_artifact`] leaves an unchanged file alone: cargo takes
/// a *directory* to mean the newest mtime anywhere under it, so rewriting identical
/// bytes on every build would make the directory permanently newer than the build
/// script's own output and rerun the script forever.
fn emit_onboarding(config: &Config) -> Result<(), String> {
    println!("cargo::rerun-if-changed={ONBOARDING_DIR}");

    let comm_data = BasicCommData {
        password: Spake2pVerifierPassword::new_from_ref(Spake2pVerifierPasswordRef::new(
            &config.commissioning.passcode.to_le_bytes(),
        )),
        discriminator: config.commissioning.discriminator,
    };

    // `DiscoveryCapabilities::BLE`, because commissioning is non-concurrent: the
    // device is reachable over BLE and nothing else until it has joined Thread. This
    // is the same value `rs-matter-stack`'s wireless network hands the boot-time
    // printer (`ThreadMatterStack::discovery_capabilities`).
    let payload = QrPayload::new(
        DiscoveryCapabilities::BLE,
        CommFlowType::Standard,
        comm_data.clone(),
        TEST_DEV_DET.vid,
        TEST_DEV_DET.pid,
        "",
        no_optional_data as NoOptionalData,
    );

    // Covers the discriminator and passcode ranges `validate` already checked, so
    // this should not be reachable - but it is the crate's own opinion of the payload
    // it is about to encode, and an invalid one encodes to a code that silently does
    // not pair.
    if !payload.is_valid() {
        return Err("the [commissioning] values do not make a valid Matter QR payload".into());
    }

    // Our payload carries no optional data, so it is 88 bits - nineteen base-38
    // characters after the `MT:` prefix - and `Qr::compute` picks version 2 for it.
    // The buffers are sized for the version 5 that `Qr::compute` tops out at (37x37
    // modules, a little over 172 bytes each), so that adding a field later does not
    // quietly turn into a `BufferTooSmall`.
    let mut payload_buf = [0; 128];
    let mut tmp_buf = [0; 512];
    let mut out_buf = [0; 512];
    let mut text_buf = [0; 8192];

    let (text, _) = payload
        .as_str(&mut payload_buf)
        .map_err(|err| format!("could not encode the QR payload: {err}"))?;

    let qr = Qr::compute(text, &mut tmp_buf, &mut out_buf)
        .map_err(|err| format!("could not compute the QR code: {err}"))?;

    // Border 4 and `invert: false` are what `Matter::print_standard_qr_code` uses, so
    // the block art in the file is what scrolls past on the console. Every renderer
    // but the ASCII one ends its lines with an ANSI reset, for the sake of the `Ansi`
    // variant's colour runs; in a file those are just stray control bytes, and the
    // half-block art carries no colour to reset.
    let (art, _) = qr
        .as_str(QrTextType::Unicode, QR_BORDER, false, &mut text_buf)
        .map_err(|err| format!("could not render the QR code as text: {err}"))?;

    let art = art.replace("\u{1b}[0m", "");

    let dir = Path::new(ONBOARDING_DIR);

    fs::create_dir_all(dir).map_err(|err| format!("could not create {ONBOARDING_DIR}: {err}"))?;

    write_artifact(
        &dir.join("pairing.txt"),
        &pairing_sheet(config, &comm_data, text, &art),
    )?;
    write_artifact(
        &dir.join("qr.svg"),
        &qr_svg(&qr, &config.device.device_name),
    )?;

    Ok(())
}

/// Write `contents` to `path`, unless it is already exactly what is there.
///
/// See [`emit_onboarding`] for why the mtime matters.
fn write_artifact(path: &Path, contents: &str) -> Result<(), String> {
    if fs::read(path).is_ok_and(|current| current == contents.as_bytes()) {
        return Ok(());
    }

    fs::write(path, contents).map_err(|err| format!("could not write {}: {err}", path.display()))
}

/// The human-readable half: the two codes, the parameters behind them, and the same
/// block art the console shows.
fn pairing_sheet(config: &Config, comm_data: &BasicCommData, payload: &str, art: &str) -> String {
    let device_name = &config.device.device_name;
    let heading = format!("{device_name} - Matter commissioning");
    let rule = "=".repeat(heading.chars().count());

    let manual = comm_data.compute_pretty_pairing_code();
    let discriminator = comm_data.discriminator;
    let passcode = config.commissioning.passcode;
    let vid = TEST_DEV_DET.vid;
    let pid = TEST_DEV_DET.pid;

    let mut out = String::new();

    let _ = write!(
        out,
        "\
{heading}
{rule}

  Manual pairing code   {manual}
  QR payload            {payload}

  Discriminator         {discriminator}
  Passcode              {passcode:08}
  Vendor / product ID   0x{vid:04X} / 0x{pid:04X} (the CSA test IDs)
  Commissioning flow    standard
  Discovery             BLE

{art}
Generated by build.rs from config.toml. `qr.svg` beside this file is the same code
as a scalable image, which is the one to print - the block art above only scans off
a dark background, the way it looks on the console.

The board prints these itself at boot over USB Serial/JTAG, and its QR payload
carries one field this one cannot: the SerialNumber, derived from the chip's factory
MAC. That is optional data no commissioner needs, so the two codes differ as strings
and pair identically.

The device is uncertified - it ships rs-matter's test attestation and the CSA test
vendor and product IDs - so every commissioner warns about it.
"
    );

    out
}

/// The QR as an SVG: one `<path>` of horizontal runs over a white ground.
///
/// Sized in millimetres rather than pixels so that printing it gives a code of a
/// known physical size; the `viewBox` is in modules, so any scale works.
fn qr_svg(qr: &Qr, device_name: &str) -> String {
    /// Printed edge length, including the quiet zone. Comfortably above the ~20 mm
    /// where a phone camera starts to struggle at arm's length.
    const SIZE_MM: u32 = 40;

    let border = i32::from(QR_BORDER);
    let modules = qr.size() as i32;
    let span = modules + border * 2;

    let mut path = String::new();

    for y in 0..modules {
        let mut x = 0;

        while x < modules {
            if !qr.get_module(x, y) {
                x += 1;
                continue;
            }

            let start = x;
            while x < modules && qr.get_module(x, y) {
                x += 1;
            }

            let _ = write!(
                path,
                "M{} {}h{}v1h-{}z",
                start + border,
                y + border,
                x - start,
                x - start
            );
        }
    }

    // `crispEdges` keeps the module boundaries from being antialiased into grey at
    // small scales, which is what makes a rendered QR hard to decode.
    format!(
        r##"<?xml version="1.0" encoding="UTF-8"?>
<svg xmlns="http://www.w3.org/2000/svg" version="1.1"
     width="{SIZE_MM}mm" height="{SIZE_MM}mm" viewBox="0 0 {span} {span}"
     shape-rendering="crispEdges">
  <title>{} - Matter commissioning QR code</title>
  <rect width="{span}" height="{span}" fill="#ffffff"/>
  <path d="{path}" fill="#000000"/>
</svg>
"##,
        escape_xml(device_name)
    )
}

/// The five predefined XML entities, for the one place a configured string reaches
/// the SVG.
fn escape_xml(text: &str) -> String {
    text.chars()
        .map(|c| match c {
            '&' => "&amp;".into(),
            '<' => "&lt;".into(),
            '>' => "&gt;".into(),
            '"' => "&quot;".into(),
            '\'' => "&apos;".into(),
            c => c.to_string(),
        })
        .collect()
}
